### PR TITLE
Yelp Review Component Merge Request

### LINKED ISSUE #6: US #5: Yelp Review Component
## Description

Given a number(representing a user's mood); generate a set of fake Yelp Reviews with a similar rating/feeling to the rating(i.e. a super happy reflection of a day for 7, and a very depressing reflection for 1). This will need an affiliated `.js` file. Then format and render this accordingly with `html, css` similar to Yelp. 

## Frontend

Take a look at Yelp.com to get an idea. This should be rendered solely off a number. See if you can generate 5 Yelp Reviews that fade in from the bottom of the screen('css' animations). Take a look at this documentation for custom components: https://www.freecodecamp.org/news/reusable-html-components-how-to-reuse-a-header-and-footer-on-a-website;.

## Backend

N/A

### PR DESCRIPTION
**Pull request by andronius-yang**
## Tracking Info

Resolves #6 

## Changes

Added review component (similar to Yelp reviews) and all associated files under `/review`

## Testing

Tested using LiveServer

## Confirmation of Change

`/review/review.html` shows a sample use case. Pressing the button displays randomized reviews and associated star values.
Screenshot 2024-04-24 180356

### CODE REVIEW

**Review by arnavkamdar — APPROVED** [review]
This looks amazing Andrew! One small bit of feedback that maybe we could try to work on - can we randomize the number of stars per review as well? Just so when we click refresh the number of stars doesn't stay the same always. I'll approve the PR anyway, but let's work towards that.

**Comment by andronius-yang** [comment]
In review.js, I’ve pregenerated 5 responses per score review. Is this kind of the idea you were thinking of? @arnavkamdar 

EDIT - Just reread the comment. The idea is that once the user selects their feeling rating, that will be the parameter to pass into the generation. Right now it is preset to 3 different values, but I’ll try adding a variable as the parameter to generating responses.

**Comment by SamvritSrinath** [comment]
Looks Very Good —> however, the animation only appears for the first quote so that needs to be revised.

**Review by SamvritSrinath — APPROVED** [review]

**Comment by andronius-yang** [comment]
> Looks Very Good —> however, the animation only appears for the first quote so that needs to be revised.

Do you mean that there's no animation after repressing the button? Or that the first press only shows the animation for the first quote? On my end all three reviews in the demo show up at the same time. I'll double check.

**Pull request merged**
