### PR TITLE
widget/naina+mialyssa/semicircle

### LINKED ISSUE #2: US #1: Semi-circular Rainbow
## Description

Taking a look at the Miro board, make a semi-circular widget that has a rainbow gradient.(Try 7 regions)

https://miro.com/app/board/uXjVMR_60ks=/

## Frontend

Make a component that allows a user to hover over 7 different regions on a semi-circular rainbow component. 

**Console.log** the colors that the user is hovering over, will help with testing
## Backend

N/A

### PR DESCRIPTION
**Pull request by mialyssa**
## Tracking Info

Resolves #2 
## Changes

- Created ~~Semicircle~~ Rectangle Gradient Widget

## Testing

- HTML/CSS Liveserver editing

## Confirmation of Change

All additions + documentation can be found in the "gradient-widget" folder.

### CODE REVIEW

**Review by mapersiani — APPROVED** [review]
Looks good. The semicircle sounds neat but definitely seems challenging to implement. The bar works well.

**Comment by arnavkamdar** [comment]
I think this looks great! My only comment was that the color changing seemed too harsh in the semi-circle file, but the rectangle gradient honestly looks perfect. Great work!

**Review by arnavkamdar — APPROVED** [review]
Looks good to me! Take a look at the above comment - if we want to continue with the semicircle route (which looks pretty clean to me honestly), we should make the colors a bit easier on the eyes and add fades.

**Review by faquanly — APPROVED** [review]

**Comment by faquanly** [comment]
Looks good to me

**Pull request merged**
