### PR TITLE
Instruction Pop up and Logo

### LINKED ISSUE #14: Interactivity
## Description

Add Directions for How to use the Widget, buttons for routing, and overall making the widget more presentable. 

## Frontend

Primarily add buttons, directions, and consistent CSS with the rest of the App. 

## Backend

<!-- What dependencies are present on the backend, are there any logic/external data required? >

### PR DESCRIPTION
**Pull request by deenap23**
## Tracking Info

Resolves #14

## Changes

- Added popup question mark
- popup window display instructions
- added  Akatsuki logo

## Testing

- Liveserver 

## Confirmation of Change

image
Updated button color: 
image

### CODE REVIEW

**Comment by deenap23** [comment]
I had trouble getting the popup on the side, so i just went ahead and put it at the bottom

**Review by faquanly — APPROVED** [review]
Deena and I worked on it yesterday, I will try to make the pop up on the side but I am having a class until noon. So I may not be able to make it by 1. Also, I think this small issue can still be fixed later on after we merge it.

**Review by mialyssa — APPROVED** [review]
The bottom placement looks good! The only thing is that when the background is yellow, it is hard to see the white button, however every other color looks fine. The functionality works great, so I think if the corners don't work out, the current placement is good. Minor suggestion, but I think the logo should go below the info button. Nice job!

**Comment by deenap23** [comment]
Just changed the color of the button to black for better readability. I also changed the order of the button and the logo and added docs.

**Comment by mialyssa** [comment]
Changes look good to me! :)

**Pull request merged**
