### PR TITLE
Integration of Gradient and Form

### LINKED ISSUE #7: Integrating Features
## Description

Integrate Features from #2 #3 

## Frontend

Consolidate the Rainbow features, ambient background and dynamic emojis. 

## Backend

N/A

### PR DESCRIPTION
**Pull request by andronius-yang**
## Tracking Info

Resolves #7 

## Changes

Gradient selection now can be inputted alongside with form. Stored under `integration/index.html`

## Testing

Liveserver Testing

## Confirmation of Change

image

### CODE REVIEW

**Review by mapersiani — APPROVED** [review]
Works very well! We might want to try making the tabbing experience better next.

**Comment by SamvritSrinath** [comment]
I believe the textbox should be bigger! We also should have a display to see when the emotion is locked(not that user-intuitive). Also, hovering over the colors doesn't change my mouse(it might be me), does anyone see this behavior?

**Review by arnavkamdar — APPROVED** [review]
Looks good to me, I've added the comments Samvrit made into issue #13

**Comment by andronius-yang** [comment]
@SamvritSrinath @deenap23 I've made my updates:

image

Here's what the selection and highlight looks like. @hfituri I've not applied the gradient change to the `integrate` folder, but I've merged it into `gradient-widget-rectangle`. The flashing between gradient change particularly affected me. I'll see if I can adjust it tomorrow.

**Pull request merged**
